language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild -project MovieTracker/movietracker.xcodeproj -scheme movietracker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test | xcpretty