language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild -workspace MovieTracker/movietracker.xcworkspace -scheme movietracker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test | xcpretty -c